# BasicCad
# BasicCAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)
* [Sub Assembly](#Sub-Assembly)
* [Final Assembly](#Final-Assembly) 

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/0d70f655203ca304cb3c5b7d/w/f55603f962f6fc74f5548a68/e/41d730c570a8d75fce9f51b6)

### Image
This is how you will write image code for INTERNALLY STORED images on your repo.   just FYI.
~~~
<img src="images/Base.jpg" alt="The Base" width="200">
~~~
<img src="https://github.com/OneCHSEngr/BasicCAD/blob/master/images/Base.jpg" width="100">

### Reflection

This was my first Onshape part and [following along with Dr. Shields made it super easy.](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4)  I learned about 
* sketching (shortcut **shift-s**)
* constructions lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut key **E**)
* linear patterns (no shortcut)

Onshape is awesome.  I found it really helpful to rename all my sketches.  It is going to be a GREAT year in engineering.

---


## Mount

### Description
This part is the mount for the caster. It is a 120mm by 120mm rectangle with a thickness of 8mm. On it, there are 5 holes, 4 of which that are symmetical, and are positioned at each corner. These holes have a diameter of 10mm. The other hole is located at the origin, and has a diameter of 25mm.
### Evidence
[The Mount in Onshape](https://cvilleschools.onshape.com/documents/fb12fb072f9d84f05ef6c69f/w/5acd12414a244aa8c7fe6ea3/e/543c0aa96815a513cbee6672)
### Image
![Screenshot 2020-10-06 at 9 39 35 PM](https://user-images.githubusercontent.com/71345176/95661728-850b9880-0aff-11eb-9f3d-cbfe78d2bbd1.png)
### Reflection
This was an easy part for me to build, simply because it was a basic shape.
Some shortcuts I learned:
Shift S (New Sketch)
C (Circle
R (New Rectangle)

---


## Fork

### Description
The fork is just a cylinder with an 80mm diameter, and that is 8mm thick. There are two prongs extruding from it that are 40mm long, 5mm wide, and 75mm tall.There are two fillets on both sides on the top, that are both 15mm, and the fork also has a 1mm fillet on the edge of both sides.Both prongs have a hole that measures 10mm in diameter, and 15mm away from the top of the prong. on the other face of the cylinder , there is a long tube that has a 15mm diameter on the interior and a 20mm on the exterior. It should also be 60mm tall, and there is a 1mm chamfer on the top of the culinder and on both edges of the base circle.
### Evidence
[The Fork in Onshape](https://cvilleschools.onshape.com/documents/18245d35fc21dcc2922b77a2/w/38f0b5cac535264c7a2ce9fd/e/04cc03635b3e5da10f165a96)
### Image
![Screenshot 2020-10-06 at 9 40 25 PM](https://user-images.githubusercontent.com/71345176/95661970-99e92b80-0b01-11eb-88ca-8026ecbebefc.png)

### Reflection
If you have trouble mirroring (M)the forks prongs, like I did,you can always choose a different plane.
Shift F was a shortcut that I found really helpful.

---


## Tire

### Description
The tire is a 20mm rectangle that has been revolved. It has an 8mm fillet on both sides.
### Evidence
[The Tire in Onshape](https://cvilleschools.onshape.com/documents/18245d35fc21dcc2922b77a2/w/38f0b5cac535264c7a2ce9fd/e/83db7f4c9b2bcb9948d0f843)
### Image
![Screenshot 2020-10-06 at 9 39 46 PM](https://user-images.githubusercontent.com/71345176/95662046-12e88300-0b02-11eb-9fbc-fd7c49e7fc8f.png)
### Reflection
I found the Rotate command (R) really helpful during this part, and I reccoment it to everyone else.

---


## Wheel

### Description
The Wheel is 20mm wide and about 5mm thick. There are 5 60 degree spokes that rotate around the origin. There is a 4mm fillet on the interior edges of the wheel.
### Evidence
[The Wheel in Onshape](https://cvilleschools.onshape.com/documents/6752f3bbeb173dab887e8f7d/w/08d58750d2eb831da6b8a9c7/e/6d4079d03af7e1f44a970047)
### Image
![Screenshot 2020-10-10 at 3 40 33 PM](https://user-images.githubusercontent.com/71345176/95663642-f6067c80-0b0e-11eb-812a-d430b41aea88.png)
### Reflection
This part was basically like the tire, but more complicated. I reccomend having a multi shape sketch to revolve.

---


## AxleCollarBearings

### Description
The Axle is a tube thats 60mm long. It has an outer diameter of 10mm and an inner diameter of 6mm. There is a 10mm deep cut in the axle that sits 4.5 mm above the origin of the front of it. This is Reflected over to the other side of the Axle.

The collar is a 10mm long tube thats outer diameter is 15mm and its inner diameter is 10mm. It has a 3mm hole on the side of it.\

The big bearing is a 5mm long tube with an outer diameter of 30mm and aninner diameter of 20mm.

The bearing is a 5mm long tube with an outer diameter of 25mm and an inner diameter of 10mm.
### Evidence
[The AxleCollarBearings](https://cvilleschools.onshape.com/documents/8820b5d006ac7554ffc4aefb/w/5ed85717ab42351bba28634a/e/868fe55b1d4705d53aa59671)
[The Big Bearing](https://cvilleschools.onshape.com/documents/cdfa513fd89b2321ad005ae6/w/9615a75935d7109ba1b5b622/e/b78a6ef39166cb4dc946966f)
[The Bearing](https://cvilleschools.onshape.com/documents/c0fa7a09c4403d292bba9850/w/a4f8b0abf85e834fcf014bb9/e/36dd27393be249f7775dc693)
### Image
![Screenshot 2020-11-06 at 11 59 39 PM](https://user-images.githubusercontent.com/71345176/98432566-77f5b100-208d-11eb-94e4-9023579b556c.png)
![Screenshot 2020-11-07 at 12 04 29 AM](https://user-images.githubusercontent.com/71345176/98432578-9065cb80-208d-11eb-8723-ee6bf7bb10a0.png)
![Screenshot 2020-11-07 at 12 06 02 AM](https://user-images.githubusercontent.com/71345176/98432587-a96e7c80-208d-11eb-95bc-e6d7b1751268.png)

### Reflection
These pieces were very easy to build, but, In the Axle piece, make sure that the 10mm cut is 4.5mm from the origin. 

---



## Sub Assembly

### Description
This is the Sub Assembly, I am preparing to build the Final Assembly. First, mate the two washers to both sides of the wheel, using a fastened mate. Then, mate the tire and the wheel together, also using a fastened mate. Finally, send the axle through the wheel, using a fastened mate.# Description
### Evidence 
[The Sub Assembly](https://cvilleschools.onshape.com/documents/c9f0132a2ced921407207cad/w/e1dd5a254344415a22f5c1e6/e/48cea90eb043cf45958f928d)
### Image
![Screenshot 2020-11-06 at 11 50 17 PM](https://user-images.githubusercontent.com/71345176/98432436-2c8ed300-208c-11eb-8d02-9f840db6dca1.png)

### Reflection
By making this Sub Assembly, it will help me create the Final Assembly much faster. 
---


##  Final Assembly

### Description
This is the Final Caster Assembly. It is all of the pieces I have made joined together to make a Caster. First, mate The Mount onto The Base using a fastened mate. Then, mate the big bearing onto the mount using a revolute mate. Next, mate the fork onto the bearing, through the Base, and through the Mount, using a revolute mate. after, mate the Wheel and Axle onto the fork using a revolute mate. Then, add collars to both sides of the Axle that is poking out of the fork. Then, add hex screws into the 4 different holes of the mount and the base. Secure those with nuts. Next, put a giant nut on the piece of the fork that is poking out. Finally, add the little tubes into the collars.
### Evidence 
[Final Assembly](https://cvilleschools.onshape.com/documents/c0fa7a09c4403d292bba9850/w/a4f8b0abf85e834fcf014bb9/e/3ff398633ee72ae307eaa8ce)
### Image
![Screenshot 2020-11-06 at 11 27 42 PM](https://user-images.githubusercontent.com/71345176/98432222-0d8f4180-208a-11eb-98c6-541d84ce0d84.png)

### Reflection
The mating was not that hard. While youre mating, I suggest making sure to check if you are mating the right sides. A shortcut for mating is (M).

---
